onlyOneBackUp: 1

indentPreamble: 1

preambleCommandsBeforeEnvironments: 1

verbatimEnvironments:
    cmhlistings: 1
    yaml: 1
    commandshell: 1
    dosprompt: 1
    lstlisting: 1

indentAfterHeadings:
    appendix:
       indentAfterThisHeading: 1
       level: 1
    section:
       indentAfterThisHeading: 1
       level: 2
    subsection:
       indentAfterThisHeading: 1
       level: 2
    yamltitle:
       indentAfterThisHeading: 1
       level: 2
    flagbox:
       indentAfterThisHeading: 1
       level: 2
    subsubsection:
       indentAfterThisHeading: 1
       level: 2
    paragraph:
       indentAfterThisHeading: 1
       level: 3

indentRules:
   titleformat:
       body: "  " 
   titlecontents:
       body: "  " 

noAdditionalIndent:
    widepage: 0

commandCodeBlocks:
    roundParenthesesAllowed: 1
    stringsAllowedBetweenArguments:
      - '\*'

modifyLineBreaks:
    commands:
        announce:
            CommandStartsOnOwnLine: 2
        index:
            CommandStartsOnOwnLine: 1
    textWrapOptions:
        columns: 90
        perCodeBlockBasis: 1
        masterDocument: 1
        afterHeading: 1
        items: 1
    removeParagraphLineBreaks:
        masterDocument: 1
        items: 1
        afterHeading: 1
        beforeTextWrap: 1

removeTrailingWhitespace:
    beforeProcessing: 1
    afterProcessing: 1

replacements:
  - 
    amalgamate: 0
  -
    substitution: s/\%+/\%/sg
    when: after
  -
    substitution: s/(\}|[a-zA-Z])\h+([a-zA-Z])/$1 $2/sg
    when: before
  -
    substitution: s/\h+(\\end\{commandshell\})/$1/sg
    when: after
